apiVersion: apps/v1
kind: Deployment
metadata:
  labels: {{ include "restapi-flask.labels" . | nindent 4 }}
  name: {{ include "restapi-flask.fullname" . }}
spec:
  replicas: {{ .Values.replicaCount | default 1 }}
  selector:
    matchLabels:
      app: {{ include "restapi-flask.fullname" . }}
  template:
    metadata:
      labels:
        app: {{ include "restapi-flask.fullname" . }}
    spec:
      containers:
        - name: api
          image: "{{ .Values.image.repository | default "restapi-flask" }}:{{ .Values.image.tag | default "latest" }}"
          {{- if .Values.environmentVariables }}
          env:
            {{- toYaml .Values.environmentVariables | nindent 12 }}
          {{- end }}
          {{- if .Values.environmentVariablesFrom }}
          envFrom:
            {{- toYaml .Values.environmentVariablesFrom | nindent 12 }}
          {{- end }}
          {{- if .Values.livenessProbe }}
          livenessProbe:
            {{- toYaml .Values.livenessProbe | nindent 12 }}
          {{- else }}
          livenessProbe:
            httpGet:
              path: /health
              port: {{ .Values.appPort | default 5000 }}
          {{- end }} 
          {{- if .Values.readinessProbe }}
          readinessProbe:
            {{- toYaml .Values.readinessProbe | nindent 12 }}
          {{- else }}
          readinessProbe:
            httpGet:
              path: /health
              port: {{ .Values.appPort | default 5000 }}
          {{- end }}
      {{- if .Values.imagePullSecrets }}
      imagePullSecrets:
        - name: {{ .Values.imagePullSecrets }}
      {{- end }}
